SET IDENTITY_INSERT [dbo].[VehicleModel] ON
INSERT INTO [dbo].[VehicleModel] ([Id], [MakeId], [Name], [Abrv]) VALUES (1, 1, N'A1', N'AD1A1     ')
INSERT INTO [dbo].[VehicleModel] ([Id], [MakeId], [Name], [Abrv]) VALUES (2, 1, N'A3', N'AD2A3     ')
INSERT INTO [dbo].[VehicleModel] ([Id], [MakeId], [Name], [Abrv]) VALUES (3, 1, N'A4', N'AD3A4     ')
INSERT INTO [dbo].[VehicleModel] ([Id], [MakeId], [Name], [Abrv]) VALUES (4, 1, N'A5', N'AD4A5     ')
INSERT INTO [dbo].[VehicleModel] ([Id], [MakeId], [Name], [Abrv]) VALUES (5, 1, N'A6', N'AD5A6     ')
INSERT INTO [dbo].[VehicleModel] ([Id], [MakeId], [Name], [Abrv]) VALUES (6, 1, N'A7', N'AD6A7     ')
INSERT INTO [dbo].[VehicleModel] ([Id], [MakeId], [Name], [Abrv]) VALUES (7, 1, N'A8', N'AD7A8     ')
INSERT INTO [dbo].[VehicleModel] ([Id], [MakeId], [Name], [Abrv]) VALUES (8, 1, N'Q2', N'AD8Q2     ')
INSERT INTO [dbo].[VehicleModel] ([Id], [MakeId], [Name], [Abrv]) VALUES (9, 1, N'Q3', N'AD9Q3     ')
INSERT INTO [dbo].[VehicleModel] ([Id], [MakeId], [Name], [Abrv]) VALUES (10, 1, N'Q5', N'AD10Q5    ')
INSERT INTO [dbo].[VehicleModel] ([Id], [MakeId], [Name], [Abrv]) VALUES (11, 2, N'Kuga', N'FD11K     ')
INSERT INTO [dbo].[VehicleModel] ([Id], [MakeId], [Name], [Abrv]) VALUES (12, 2, N'Puma', N'FD12P     ')
INSERT INTO [dbo].[VehicleModel] ([Id], [MakeId], [Name], [Abrv]) VALUES (13, 2, N'Mondeo', N'FD13M     ')
INSERT INTO [dbo].[VehicleModel] ([Id], [MakeId], [Name], [Abrv]) VALUES (14, 2, N'Ranger', N'FD14R     ')
INSERT INTO [dbo].[VehicleModel] ([Id], [MakeId], [Name], [Abrv]) VALUES (15, 2, N'Fiesta VAN', N'FD15FV    ')
INSERT INTO [dbo].[VehicleModel] ([Id], [MakeId], [Name], [Abrv]) VALUES (16, 2, N'Focus ST', N'FD16ST    ')
INSERT INTO [dbo].[VehicleModel] ([Id], [MakeId], [Name], [Abrv]) VALUES (17, 2, N'Renger Raptor', N'FD17RR    ')
INSERT INTO [dbo].[VehicleModel] ([Id], [MakeId], [Name], [Abrv]) VALUES (18, 2, N'Fiesta ST', N'FD18ST    ')
INSERT INTO [dbo].[VehicleModel] ([Id], [MakeId], [Name], [Abrv]) VALUES (19, 2, N'EcoSport', N'FD19ES    ')
INSERT INTO [dbo].[VehicleModel] ([Id], [MakeId], [Name], [Abrv]) VALUES (20, 2, N'Mustang', N'FD20M     ')
INSERT INTO [dbo].[VehicleModel] ([Id], [MakeId], [Name], [Abrv]) VALUES (21, 3, N'Azera', N'HD21A     ')
INSERT INTO [dbo].[VehicleModel] ([Id], [MakeId], [Name], [Abrv]) VALUES (22, 3, N'Sonata', N'HD22S     ')
INSERT INTO [dbo].[VehicleModel] ([Id], [MakeId], [Name], [Abrv]) VALUES (23, 3, N'i40', N'HD23i40   ')
INSERT INTO [dbo].[VehicleModel] ([Id], [MakeId], [Name], [Abrv]) VALUES (24, 3, N'Veloser', N'HD24V     ')
INSERT INTO [dbo].[VehicleModel] ([Id], [MakeId], [Name], [Abrv]) VALUES (25, 3, N'i30', N'HD25i30   ')
INSERT INTO [dbo].[VehicleModel] ([Id], [MakeId], [Name], [Abrv]) VALUES (26, 3, N'Accent', N'HD26A     ')
INSERT INTO [dbo].[VehicleModel] ([Id], [MakeId], [Name], [Abrv]) VALUES (27, 3, N'i20', N'HD28i20   ')
INSERT INTO [dbo].[VehicleModel] ([Id], [MakeId], [Name], [Abrv]) VALUES (28, 3, N'Xcent', N'HD28X     ')
INSERT INTO [dbo].[VehicleModel] ([Id], [MakeId], [Name], [Abrv]) VALUES (29, 3, N'Palisade', N'HD29P     ')
INSERT INTO [dbo].[VehicleModel] ([Id], [MakeId], [Name], [Abrv]) VALUES (30, 3, N'Santa Fe', N'HD30SF    ')
INSERT INTO [dbo].[VehicleModel] ([Id], [MakeId], [Name], [Abrv]) VALUES (31, 4, N'Aygo', N'TY31A     ')
INSERT INTO [dbo].[VehicleModel] ([Id], [MakeId], [Name], [Abrv]) VALUES (32, 4, N'Yaris', N'TY32Y     ')
INSERT INTO [dbo].[VehicleModel] ([Id], [MakeId], [Name], [Abrv]) VALUES (33, 4, N'Corolla', N'TY33C     ')
INSERT INTO [dbo].[VehicleModel] ([Id], [MakeId], [Name], [Abrv]) VALUES (34, 4, N'Camry', N'TY34C     ')
INSERT INTO [dbo].[VehicleModel] ([Id], [MakeId], [Name], [Abrv]) VALUES (35, 4, N'RAV4', N'TY35R4    ')
INSERT INTO [dbo].[VehicleModel] ([Id], [MakeId], [Name], [Abrv]) VALUES (36, 4, N'Hilux', N'TY36H     ')
INSERT INTO [dbo].[VehicleModel] ([Id], [MakeId], [Name], [Abrv]) VALUES (37, 4, N'Land Cruiser', N'TY37LC    ')
INSERT INTO [dbo].[VehicleModel] ([Id], [MakeId], [Name], [Abrv]) VALUES (38, 4, N'Prius', N'TY38P     ')
INSERT INTO [dbo].[VehicleModel] ([Id], [MakeId], [Name], [Abrv]) VALUES (39, 4, N'Corolla Sedan', N'TY39CS    ')
INSERT INTO [dbo].[VehicleModel] ([Id], [MakeId], [Name], [Abrv]) VALUES (40, 4, N'Proace Verso', N'TY40PV    ')
INSERT INTO [dbo].[VehicleModel] ([Id], [MakeId], [Name], [Abrv]) VALUES (41, 5, N'Polo', N'VG41P     ')
INSERT INTO [dbo].[VehicleModel] ([Id], [MakeId], [Name], [Abrv]) VALUES (42, 5, N'T-Cross', N'VG41TC    ')
INSERT INTO [dbo].[VehicleModel] ([Id], [MakeId], [Name], [Abrv]) VALUES (43, 5, N'ID.3', N'VG43ID3   ')
INSERT INTO [dbo].[VehicleModel] ([Id], [MakeId], [Name], [Abrv]) VALUES (44, 5, N'T-Roc', N'VG44TR    ')
INSERT INTO [dbo].[VehicleModel] ([Id], [MakeId], [Name], [Abrv]) VALUES (45, 5, N'Golf', N'VG45G     ')
INSERT INTO [dbo].[VehicleModel] ([Id], [MakeId], [Name], [Abrv]) VALUES (46, 5, N'ID.4', N'VG46ID4   ')
INSERT INTO [dbo].[VehicleModel] ([Id], [MakeId], [Name], [Abrv]) VALUES (47, 5, N'Touran', N'VG47T     ')
INSERT INTO [dbo].[VehicleModel] ([Id], [MakeId], [Name], [Abrv]) VALUES (48, 5, N'Passat', N'VG48P     ')
INSERT INTO [dbo].[VehicleModel] ([Id], [MakeId], [Name], [Abrv]) VALUES (49, 5, N'Arteon', N'VG49A     ')
INSERT INTO [dbo].[VehicleModel] ([Id], [MakeId], [Name], [Abrv]) VALUES (50, 5, N'Touareg', N'VG50T     ')
SET IDENTITY_INSERT [dbo].[VehicleModel] OFF
